name: CI
on:
  push: { branches: [main] }
  pull_request: { branches: [main] }
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Python check
        run: |
          python -m pip install --upgrade pip
          python - <<'PY'
print("✅ python ok")
PY
      - name: Node check
        run: |
          node -v
          npm -v || true
